- docs/integrations/windows.md
Update NXLog documentation to use `om_tcp` and “octet framing” to send events (with the not so well named option `OutputType Syslog_TLS`).
> Operation Center: Update Windows NXLog config to use TCP

- docs/integrations/fortigate.md
- docs/integrations/paloalto.md
Update Fortigate an Palo Alto Networks configurations to push logs to the internal log collector using the latest version of the syslog protocol (RFC5424). This will solve issues with some parsing & process name.
> Fortigate & PAN: Use RFC5424 syslog protocol over TCP

- docs/integrations/auditbeat_linux.md
Those extra directories are required due to the default option `recursive: false` which avoid monitoring subdirectory.
> Monitore directories used by cron

- .github/workflows/upload-preview.yaml
This fixes an issue where a new page is added in a PR, and then removed from the same PR. Always create a clean environment.
> fix: Delete existing previews on OVH before pushing a new one

- .github/workflows/preview.yaml
- .github/workflows/upload-preview.yaml
- mkdocs.yml
API documentation URLs were moved from `/apis` and `/api/xxx` to a new set of URLs (more information in #153). This PR only add redirections for the old set of URLs.
> fix: Add some redirections for API documentations

- src/sekoiaio.scss
~~It's an interesting subject, but I don't know which solution to choose:~~
~~1/ initially I thought we could have a black background. 
But I'm afraid that there are black code snippets somewhere else in the documentation which would make the code invisible.~~ 
~~2/ So I thought of a grey background, which would work with both types of code colours (and would keep a good contrast).~~ 
~~3/ Alternatively a blue background that reminds the colour of the header navigation.~~
~~4/ But otherwise nothing, to have a pink like the colour of the right section. But I feel like that's what's been tried to be changed. Maybe you want me to remove that pink colour on the right section too?~~
~~(my commit implements solution 3)~~
Let me know :)  
Poke @squioc
> suggest a new background for code

- docs/develop/rest_api/community.md
- docs/develop/rest_api/dashboard.md
- docs/develop/rest_api/identity_and_authentication.md
- docs/develop/rest_api/intelligence_center/enrichments.md
- docs/develop/rest_api/intelligence_center/intelligence.md
- docs/develop/rest_api/notification.md
- docs/develop/rest_api/operation_center/alert.md
- docs/develop/rest_api/operation_center/assets.md
- docs/develop/rest_api/operation_center/configuration.md
- docs/develop/rest_api/operation_center/parser.md
- docs/develop/rest_api/playbooks.md
This way, only “public” documentation for our REST APIs will be shown (hide internal endpoints and non-usable endpoints for the general public).
> feat: Only show “public” endpoints in REST API documentations

- .github/workflows/update-intakes-documentation.yaml
- scripts/update_mkdocs/templates/intake.md.jinja
- scripts/update_mkdocs/update_mkdocs.py
Creates a new GitHub Actions workflow that will be triggered by the `intake-format` repository (via a `repository_dispatch` event). By using a dedicated GitHub App, we are limiting allowed rights to this repository.
When a `repository_dispatch` event is received, this workflow will be executed and will generates intakes documentation and creates a new pull request (in the future, this PR might be auto-merged).
To work as expected, this requires https://github.com/SEKOIA-IO/intake-formats/pull/35 to be merged.
> ci: Add a new GitHub Actions script to update intakes documentation

- .github/workflows/delete-preview.yaml
- .github/workflows/deploy-public-website.yaml
- .github/workflows/upload-preview.yaml
- mkdocs.yml
- poetry.lock
Remove all content that was removed from the repository before uploading new generated files. This way, we won’t make any old content available on `docs.sekoia.io`.
This PR also adds a few redirections for old integration pages (that are still referenced in Google for example).
Finally, replace `StephaneBour/actions-ovh-storage` (thanks for the work!) action by direct calls to `swift`.
> Remove old files on public website before uploading new ones

- docs/operation_center/rules_catalog.md
The value of `timespan` can currently be set up to a maximum of `24h`.
> update(correlation rules): maximum value of timespan

- src/sekoiaio.scss
While reading a doc I noticed that the separation between the header and the content was not very clear, and hindered a bit the reading
https://user-images.githubusercontent.com/66947157/177781240-ff1b53be-9a28-4b3c-991a-e0583737b912.mov
https://user-images.githubusercontent.com/66947157/177781349-54251744-e188-44a6-af3d-5f14f59bdaa4.mov
> Add box shadow on header to make content more readable

- docs/xdr/features/collect/integrations/endpoint/sekoiaio.md
- mkdocs.yml
Proposal to move the SEKOIA.IO Agent documentation from the “ingestion methods” category to the “integrations” section.
BTW, we should also find a way to make this new agent more visible in the documentation (via use cases?).
> feat: Move SEKOIA.IO Agent documentation to integrations

- docs/xdr/features/investigate/alerts.md
Following the UPS sync report I added the "Similar alerts" section to the "Alert" documentation page
> Add similar alerts to Alerts page

- docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_cloudtrail.md
Refresh the documentation to use the new connector, using notifications, to pull the last CloudTrail logs.
> AWS: refresh the CloudTrail documentation 

- docs/xdr/features/collect/integrations/endpoint/sophos_edr.md
Document the configuration of the Sophos EDR connector.
Replace the old (imperfect) way to pull the events.
> Sophos: change the way to pull the events

- docs/xdr/features/collect/integrations/endpoint/sophos_edr.md
Fix the link that redirect to the trigger configuration
> SophosEDR: fix link to trigger documentation

- mkdocs.yml
fix for https://chat.sekoia.fr/sekoia/pl/9yzwcdne7ibtmcc6z7jtu3go4c
to
> Fix(vectra): Page title

- _shared_content/automate/index.md
Fix a typo and remove "Symphony Operator" from role suggestions since this is not needed.
> Playbooks: fix typo and role recommandation

- .github/workflows/delete-preview.yaml
- .github/workflows/upload-preview.yaml
See breaking changes: https://github.com/actions/github-script#breaking-changes-in-v5
> As part of this update, the Octokit context available via github no longer has REST methods directly. These methods are available via github.rest.*
> fix: Fixes preview workflows

- docs/xdr/features/collect/integrations/application/sekoiaio_activity_logs.md
Fix a typo (a list was not correctly displayed)
> fix(sekoia-io-activites-logs): fix a typo

- docs/xdr/features/collect/integrations/cloud_and_saas/office365/o365.md
- mkdocs.yml
add section to describe how to turn on Defender events in Office365 audit logs.
add entry in the menu to point Microsoft Defender for 0365.
> Office365: document Microsoft Defender for 0365

- docs/xdr/features/collect/integrations/generic/cef.md
Fix the link to the specification.
The old one is dead.
> CEF: fix the link to the specification

- docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_flow_logs.md
Update the procedure to forward VPC flowlogs with the S3 logs connector (not the deprecated one).
> AWS: update the AWS VPC flow logs documentation

- docs/xdr/features/collect/integrations/cloud_and_saas/okta_system_log.md
- mkdocs.yml
update the 'Pull events' section to use the OKTA connector instead of the playbook template
> OKTA: update the documentation

- docs/cti/develop/rest_api/aws-gateway.md
- docs/cti/develop/rest_api/edl-gateway.md
- mkdocs.yml
Even tough the whole AWS integration is not available for customers, I wanted to add the doc for the API endpoint used. Since those endpoints are in production, it could be used internally or if a customer is interested.
Originally, I wanted to add it to this [page](https://docs.sekoia.io/cti/develop/rest_api/intelligence/) but it doesn't seems possible natively.
> docs(aws-gateway): add endpoint documentation for API

- docs/xdr/features/collect/integrations/cloud_and_saas/netskope_events.md
- Specify the integration use the APIv2 of the Netskope platform
- List the required scopes and their privilege to use.
> Netskope: add the version of the API used and the permission required

- docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
add warning about to allow SEKOIA.IO's IPs to access the tenant and point to the FAQ to get these IPs
> Cybereason: Add note about IP filtering on Cybereason's instances

- docs/xdr/features/collect/integrations/network/cisco/cisco_nx_os.md
Fix the included suggestion of rules in the documentation of Cisco NX OS (Currently, it's the suggestion of rules for Cisco Secure Firewall).
> Cisco: fix suggested rules

- docs/xdr/features/collect/integrations/endpoint/sekoiaio.md
Add comment to help users stopping auditd when `sudo systemctl stop auditd` fails.
I got this issue on a brand new CentOS VM.
> feat: Fallback solution to stop audit deamon

- docs/xdr/features/collect/integrations/application/apache.md
- docs/xdr/features/collect/integrations/application/freeradius.md
- docs/xdr/features/collect/integrations/email/fortimail.md
- docs/xdr/features/collect/integrations/endpoint/auditbeat_linux.md
- docs/xdr/features/collect/integrations/endpoint/cybereason_malop_activity.md
- docs/xdr/features/collect/integrations/endpoint/ibm_aix.md
- docs/xdr/features/collect/integrations/endpoint/symantec_epp.md
- docs/xdr/features/collect/integrations/endpoint/trend_micro_deep_security.md
- docs/xdr/features/collect/integrations/endpoint/windows.md
- docs/xdr/features/collect/integrations/network/cisco/cisco_asa.md
- docs/xdr/features/collect/integrations/network/cisco/cisco_meraki_mx.md
- docs/xdr/features/collect/integrations/network/cisco/cisco_nx_os.md
- docs/xdr/features/collect/integrations/network/f5-big-ip.md
- docs/xdr/features/collect/integrations/network/forcepoint_web_gateway.md
- docs/xdr/features/collect/integrations/network/fortigate.md
- docs/xdr/features/collect/integrations/network/fortiproxy.md
- docs/xdr/features/collect/integrations/network/fortiweb.md
- docs/xdr/features/collect/integrations/network/gatewatcher_aioniq.md
- docs/xdr/features/collect/integrations/network/infoblox_ddi.md
- docs/xdr/features/collect/integrations/network/microsoft_always_on_vpn.md
- docs/xdr/features/collect/integrations/network/paloalto.md
- docs/xdr/features/collect/integrations/network/pulse.md
- docs/xdr/features/collect/integrations/network/sonicwall_fw.md
- docs/xdr/features/collect/integrations/network/sophos_fw.md
- docs/xdr/features/collect/integrations/network/watchguard_firebox.md
I suggest replacing, when possible, all redirections to the Rsyslog documentation with the SEKOIA.IO docker concentrator documentation.
> Doc: redirect the user to SEKOIA.IO docker concentrator doc

- docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-network.md
When I tried to setup the _Cloudflare Gateway Network_ integration, [the API request provided in the documentation](https://docs.sekoia.io/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-http/#create-a-logpush-job) failed with an error message.
Gateway Network is an [_account-scoped_ dataset](https://developers.cloudflare.com/logs/reference/log-fields/account/), but [the documentation](https://docs.sekoia.io/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-network/#create-a-logpush-job) currently uses the endpoint for _zone-scoped_ datasets.
This PR updates the API request to use the endpoint for account-scoped datasets.
I tested the updated `curl` command-line on a Cloudflare account and the logpush job was successfully …
> Fix Cloudflare Gateway Network Logpush docs

- docs/xdr/FAQ.md
This PR updates the FAQ section to include the recently-introduced https://api.sekoia.io/outgoing-ips endpoint
> FAQ: update outgoing IP section

- _shared_content/operations_center/integrations/generated/250e4095-fa08-4101-bb02-e72f870fcbd1.md
- _shared_content/operations_center/integrations/generated/2b13307b-7439-4973-900a-2b58303cac90.md
- _shared_content/operations_center/integrations/generated/302065ea-0491-41cf-a472-09b59799c55d.md
- _shared_content/operations_center/integrations/generated/3c7057d3-4689-4fae-8033-6f1f887a70f2.md
- _shared_content/operations_center/integrations/generated/3e060900-4004-4754-a597-d2944a601930.md
- _shared_content/operations_center/integrations/generated/40deb162-6bb1-4635-9c99-5c2de7e1d340.md
- _shared_content/operations_center/integrations/generated/6b8cb346-6605-4240-ac15-3828627ba899.md
- _shared_content/operations_center/integrations/generated/8a9894f8-d7bc-4c06-b96a-8808b3c6cade.md
- _shared_content/operations_center/integrations/generated/98fa7079-41ae-4033-a93f-bbd70d114188.md
- _shared_content/operations_center/integrations/generated/99da26fc-bf7b-4e5b-a76c-408472fcfebb.md
- _shared_content/operations_center/integrations/generated/bf8867ee-43b7-444c-9475-a7f43754ab6d.md
- _shared_content/operations_center/integrations/generated/c10307ea-5dd1-45c6-85aa-2a6a900df99b.md
- _shared_content/operations_center/integrations/generated/ccf942fe-c839-42be-a081-5c3f946e80f5.md
- _shared_content/operations_center/integrations/generated/d2725f97-0c7b-4942-a847-983f38efb8ff.md
- _shared_content/operations_center/integrations/generated/e4a758fc-7620-49e6-b8ed-b7fb3d7fa232.md
- scripts/update_mkdocs/update_mkdocs.py
The script was failing from one week (see [Update intakes documentation GA](https://github.com/SEKOIA-IO/documentation/actions/workflows/update-intakes-documentation.yaml)) after fixing formats against some compliances.
> Script: make update_mkdocs more resilient against empty taxonomy

- docs/xdr/features/collect/ingestion_methods/https.md
add examples of forwarding events through HTTPS method with the intake key in the query string
> HTTP Ingestion method: add examples with the intake key in the query string

- mkdocs.yml
I had to remove the link "Microsoft Defender for Endpoints" since the name was also written in the section "Microsoft 365 Defender" which is the right name for this product.
> fix(link-m365d): remove link for endpoints

- docs/xdr/features/collect/integrations/network/citrix_adc.md
US format mentioned, because there's only a choice between `MMDDYYYY` and `DDMMYYYY`, and only the former was used while creating the parser
> Update Citrix docs

- docs/javascript/sekoiaio.js
- theme/overrides/home.html
Their (often too large) cookie may block our users to access our StatusPage
> Remove Sleekplan

- mkdocs.yml
add a redirection as the documentation for Trend Micro Deep security has moved
> Trend Micro: add redirection

- docs/xdr/features/collect/integrations/cloud_and_saas/google/google_reports.md
- List the supported applications
- Add the limitation about the collect
> Google: list the supported applications 

- docs/xdr/features/collect/ingestion_methods/https.md
Add a simple documentation on how to send events using the `/array` endpoint of the HTTP collector.
> Document `/array` HTTP endpoint

- _shared_content/intelligence_center/integrations/opencti.md
Improve OpenCTI documentation with more value in `CONNECTOR_SCOPE` field
> Improve OpenCTI documentation

- mkdocs.yml
add redirection to the previous location of the documentation for Netskope Events integration
> Netskope: add redirection to the previous location of the documentation

- docs/xdr/features/collect/integrations/endpoint/auditbeat_linux.md
Modify doc for Auditbeat v8.x.
Naming of files is now different when using `output.file`. If you define the name with `auditbeat`, the name will be in fact `auditbeat-{date}.ndjson`. It was needed to update Rsyslog config file in order to read only the file `auditbeat-{date}.ndjson` and not all the files that have been rotated by auditbeat.
I tried to have only one unique file instead of having 7 rotating file but that's not possible, the strict minimum is 2.
More information [here](https://www.elastic.co/guide/en/beats/auditbeat/current/file-output.html):
> feat(auditbeat): modify for v8 and new file naming

- docs/xdr/FAQ/Detection_qa.md
- docs/xdr/FAQ/Rules_qa.md
- docs/xdr/features/detect/built_in_detection_rules.md
- docs/xdr/features/detect/rules_catalog.md
- mkdocs.yml
> feat(doc): Detection FAQ

- docs/xdr/features/detect/built_in_detection_rules.md
- docs/xdr/features/detect/rules_catalog.md
New links to the new FAQ are broken.
> fix(doc): FAQ url typo

- .gitignore
- _shared_content/automate/actions.md
- _shared_content/intelligence_center/consume/telemetry.md
- docs/getting_started/index.md
- docs/getting_started/manage_users.md
- docs/getting_started/sso/azure.md
- docs/getting_started/sso/okta.md
- docs/xdr/features/collect/ingestion_methods/https/logstash.md
- docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_files.md
- docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_front_door.md
- docs/xdr/features/collect/integrations/cloud_and_saas/cato_sase.md
- docs/xdr/features/collect/integrations/cloud_and_saas/netskope/netskope_events.md
- docs/xdr/features/collect/integrations/endpoint/crowdstrike_falcon.md
- docs/xdr/features/collect/integrations/endpoint/linux.md
- docs/xdr/features/collect/integrations/endpoint/sentinelone.md
- docs/xdr/features/detect/rules_catalog.md
- docs/xdr/usecases/playbook/Add_UserAgent_in_comment.md
- docs/xdr/usecases/playbook/ExtractIP_from_Url_country.md
- docs/xdr/usecases/playbook/Get_events_information_from_alert.md
- docs/xdr/usecases/playbook/whoIs.md
- mkdocs.yml
- Fix broken links
- Add "Icon?" to .gitignore for MacOS
- ~ Update doc according to new permissions
> fix(broken-links-2): fix links and add icon? to gitignore

- docs/xdr/features/collect/integrations/endpoint/kaspersky_endpoint_security.md
- fix the steps in order that the numeral list works
- fix the name of the second part of the configuration
> Kapersky: fix the documentation

- docs/xdr/features/collect/integrations/network/suricata.md
Following [this ticket](https://sekoia8055.zendesk.com/agent/tickets/3246)
> Improve suricata doc

- docs/xdr/features/collect/integrations/application/apache.md
- Remove duplicated `log samples` section
- List the supported events
- point to the Sekoia.io forwarder documentation (instead of rsyslog)
> Apache: Update the Apache documentation

- _shared_content/operations_center/integrations/cisco_umbrella_set_aws_forwarding.md
- docs/xdr/features/collect/integrations/cloud_and_saas/cisco_umbrella/umbrella_dns.md
- docs/xdr/features/collect/integrations/cloud_and_saas/cisco_umbrella/umbrella_ip.md
- docs/xdr/features/collect/integrations/cloud_and_saas/cisco_umbrella/umbrella_proxy.md
update Cisco Umbrella documentation to use AWS S3 buckets to collect the events
> Cisco: Refresh Cisco Umbrella documentations

- docs/xdr/features/investigate/querying_events.md
- docs/xdr/usecases/playbook/Add_UserAgent_in_comment.md
Remove references to fields that should no longer be used.
> fix: remove references to legacy fields

- docs/getting_started/manage_api_keys.md
- Add expiration dates 
- Change roles to permissions 
- Add sections about shorter API keys
> Update API keys content 

- docs/xdr/features/collect/integrations/network/stormshield_network_security.md
According to the last updates from Stormshield
> Stormshield: update the procedure to forward Stormshield SNS events

- docs/xdr/features/collect/assets.md
https://storage.gra.cloud.ovh.net/v1/AUTH_741841e1c7da4c50a76152cbc2609bd1/sekoiaio-documentation-previews/2018/xdr/features/collect/assets/#attach-edr-agent-ids-to-host
> Add EDR agent ID discovery rule

- docs/integration/categories/network_security/gatewatcher_aioniq.md
- plugins/intakes_by_uuid.py
Add the ability to redirect to the same documentation when having several incompatible formats for a same product/integration.
e.g: For GateWatcher AIONIQ, we currently support two formats: The legacy one (V102) and the ECS-like format (v103).
> Integration redirection: allow redirect to a same documentation from several formats

- docs/xdr/features/investigate/sekoia_operating_language.md
Docs used a mix of quotation marks -- some incorrect, other inconsistent. I have standardised on `'`
> standardising use of quotations in for SOL docs

- docs/integration/categories/network/umbrella_dns.md
Add back the instruction to create the Cisco Umbrella DNS logs collect through a playbook
> Umbrella DNS: update the way to collect events

- docs/integration/ingestion_methods/syslog/rsyslog.md
added noteblock with instructions for allowing syslog to communicate to port 11514
> Add selinux instructions for relp
