docs/integrations/windows.md
Fix a typo and simplify one configuration example
=> Update windows intake configuration

docs/intelligence_center/api.md, docs/intelligence_center/integrations.md, mkdocs.yml
Adds a page about external integrations for the intelligence center.
@otetard Please wait for Gaël's approval before merging. Of course don't hesitate to review it ;-)
=> feat: IC external integrations

docs/integrations/bind.md
_Please wait for this new intake format to be deployed on production before merging this PR._
=> Add BIND integration for Operation Center

docs/intelligence_center/api.md
Add a paragraph on how to use the TAXII endpoints.
=> Add TAXII documentation

docs/operation_center/faq.md, mkdocs.yml
=> Add Operation Center FAQ

docs/integrations/fortiproxy.md, docs/integrations/index.md, mkdocs.yml
Added the documentation for the FortiProxy intake.
**Warning** : This intake in not public yet
=> feat(documentation): Added fortiproxy intake documentation

docs/integrations/auditbeat_linux.md, docs/integrations/transport/rsyslog.md
I added MaxMessageSize in two file.
I verified it works on a VM
=> fix(rsyslog): Add MaxMessageSize in conf

docs/intelligence_center/integrations.md
Link to OpenCTI github repo for connector was KO
=> change opencti link

docs/operation_center/rules_catalog.md
=> update(rules catalog): introduce sigma

docs/integrations/auditbeat_linux.md
=> Remove '$' in command

mkdocs.yml
Minor changes to :
- increase date
- fix the twitter handler
=> Update Copyright date and Twitter handle

docs/releases/index.md
This PR updates the release root page to harmonize the links
=> Harmony in links of release page

src/sekoiaio.scss, theme/overrides/home.html
The home page should be now a little be more responsive.
=> The home page more responsive page

docs/integrations/azure_ad.md, docs/integrations/azure_linux.md, docs/integrations/azure_mysql.md, docs/integrations/azure_windows.md
Azure : 
* Changed name `company-sekoiaiocheckpoint` to `sekoiaiocheckpoint`
* Fixed a typo
=> fix(Azure): name too long and typos

docs/integrations/sekoiaio_activity_logs.md, mkdocs.yml
Add the documentation how to setup SEKOIA.IO activity logs in a community.
=> add documentation about the SEKOIA.IO activity logs

mkdocs.yml
Move the documentation for the activity logs from the Applications section to a new SEKOIA.IO section
=> SEKOIA.IO Activity logs: update TOC

.github/workflows/upload-preview.yaml, poetry.lock
Update Material for MkDocs to the latest version.
=> chore: Refresh `poetry.lock`

docs/intelligence_center/api.md
Adds documentation about the feed format
=> feat: Add feed format documentation

docs/develop/guides/filtering.md, mkdocs.yml, theme/overrides/develop/index.html
Add a small documentation on our match filter used by many of our endpoints
=> Document the match filter exposed by our API REST

docs/operation_center/integration_catalog/email/vade.md, mkdocs.yml
Just created the vade for M365 documentation
=> Create vade for M365 documentation

docs/operation_center/integration_catalog/email/vade.md
=> Added empty line for better list display

scripts/update_mkdocs/update_mkdocs.py
With this changes, script will avoid to produce such kind of PR: #216
=> fix: Sort items in of `update_mkdocs` script to avoid useless diffs

docs/operation_center/intakes.md
- Added a more detailed part about the integrations catalog and intake_key
- Changed gif to pictures more up to date
=> Updated intakes.md

docs/operation_center/integration_catalog/cloud_and_saas/aws/aws_cloudtrail.md, docs/operation_center/integration_catalog/cloud_and_saas/aws/aws_flow_logs.md
Update the documentation of AWS Integrations with the new triggers.
=> Integrations: update the documentation of AWS integrations

docs/operation_center/rules_catalog.md
Add new supported modifiers to the documentation
=> Rules Catalog: add new Sigma modifiers

docs/operation_center/integration_catalog/network/netfilter.md
Fix an error in a iptables syntax
=> fix(netfilter): fix a command for iptables

docs/operation_center/integration_catalog/endpoint/cybereason_malop.md, docs/operation_center/integration_catalog/generated/cybereason-malop_do_not_edit_manually.md, mkdocs.yml
Explain how to forward MalOp activities to SEKOIA.IO
=> Document the CybeReason MalOp integration

docs/operation_center/integration_catalog/cloud_and_saas/o365.md
Add the license level required for 0365 intake to be able to fetch O365 activities.
=> Integration: Add license level required for 0365

docs/intelligence_center/api.md
I introduced a small paragaph in the IC/API documentation to explain the `modified_after` parameter.
=> document Modified_after in IC/API

scripts/update_mkdocs/templates/intake.md.jinja
A little fix in the template according @ka0ula's comment
=> Scripts: fix the template

docs/operation_center/integration_catalog/cloud_and_saas/cloudflare/cloudflare.md, mkdocs.yml
Add a section about how to forward to SEKOIA.IO with logpush
=> CloudFlare: add the configuration for logpush

_shared_content/automate/library/aws.md, docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_s3_logs.md, mkdocs.yml
Add documentation about the connector S3 for logs
=> AWS: documentation about S3 for logs

docs/xdr/features/collect/ingestion_methods/https.md
Add a section to explain how to use endpoints for plain events.
=> HTTPSCollector: add section about the plain endpoints

_shared_content/operations_center/integrations/generated/proofpoint-tap_do_not_edit_manually.md, docs/xdr/features/collect/integrations/email/proofpoint_tap.md, mkdocs.yml
Add the documentation to set the integration for Proofpoint TAP
=> ProofPoint: add the documentation for TAP

docs/xdr/features/collect/ingestion_methods/https.md
Document the ability to supply the intake key as HTTP Basic Auth
=> Http Ingestion: add the HTTP Basic Auth

docs/xdr/features/collect/ingestion_methods/https.md
Add the endpoint for json-arrays
Reorganize the page to be clearer
=> HTTPIngestion: /jsons and reorganization

docs/xdr/features/collect/ingestion_methods/https.md
Missing authentication information for the json-array endpoint
=> HTTPIngestion: add some missing informations

docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-dns-logs.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-firewall-events.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-http-requests.md
Add some information to configure events forwarding with Cloudflare
=> update(cloudflare-integration): add some information for config

_shared_content/operations_center/integrations/cloudflare_necessary_info.md, _shared_content/operations_center/integrations/cloudflare_useful_api_endpoints.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-dns-logs.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-firewall-events.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-http-requests.md
* Added info to get fields depending on the customer subscription
* Added shared info in specific files
=> update(cloudflare integration): add more info

docs/xdr/features/collect/integrations/network/infoblox_ddi.md, mkdocs.yml
Add documentation for Infoblox DDI
=> Infoblox: add documentation

docs/xdr/usecases/playbook/synchronize_alerts.md
=> Add screenshots to Playbook documentation

docs/javascript/sekoiaio.js, src/sekoiaio.scss
Changes:
- Remove auto-num of h2 titles. 
- Reduce the size of the font in the main section.
(to be discussed, this can still be improved).
=> Improve CSS style

docs/xdr/features/collect/integrations/cloud_and_saas/office365/message_trace.md
https://github.com/SekoiaLab/platform/issues/32428
=> fix(o365/messagetrace): Detail required permissions and how to troubleshoot auth

_shared_content/intelligence_center/consume/feeds.md, docs/tip/features/produce/incoming_feeds.md, mkdocs.yml
* Fix link to REST endpoint
* Replace "Feeds" with "Outgoing Feeds"
* Add Incoming feeds documentation: https://storage.gra.cloud.ovh.net/v1/AUTH_741841e1c7da4c50a76152cbc2609bd1/sekoiaio-documentation-previews/447/tip/features/produce/incoming_feeds/
=> feat: Improve feed documentation

docs/xdr/features/collect/integrations/endpoint/symantec_epp.md, mkdocs.yml
add documentation about Symantec EPP integration
=> Symantec: add Symantec EPP integration

docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_front_door.md, mkdocs.yml
Add documentation to set up log forwarding from Azure Front Door to SEKOIA.IO
=> AzureFrontDoor: add documentation

docs/xdr/features/collect/integrations/endpoint/auditbeat_linux.md
=> Fix typo on 'Fedora'

docs/xdr/features/collect/integrations/endpoint/microsoft_defender_for_endpoints.md, mkdocs.yml
add the documentation for this new format
=> MicrosoftDefenderForEndpoints: add documentation

docs/xdr/features/collect/integrations/cloud_and_saas/office365/message_trace.md
Parent task:
- https://github.com/SekoiaLab/platform/issues/32427
=> doc(Office365/MessageTrace): Add doc for OAuth.

docs/getting_started/account_security.md
=> Change to "Account settings" to better match console

docs/xdr/features/collect/integrations/network/microsoft_always_on_vpn.md, mkdocs.yml
add the documentation to configure Microsoft Always On VPN integration
=> MicrosoftAlwaysOnVPN: add documentation

docs/xdr/features/collect/integrations/network/watchguard_firebox.md, mkdocs.yml
Add documentation how to forward logs from WatchGuard Firebox to SEKOIA.IO
=> WatchGuard: add Firebox documentation

docs/xdr/features/collect/ingestion_methods/rsyslog.md
- Remove the huge titles
- Improve english
=> Enhance rsyslog documentation

docs/cti/index.md
Provide a valid index page for CTI product
=> Update CTI index

docs/xdr/features/collect/integrations/network/gatewatcher_aioniq.md, mkdocs.yml
=> GatWatcher: add AIONIQ documentation

docs/xdr/features/collect/integrations/endpoint/tehtris_edr.md, mkdocs.yml
Add the documentation to configure the collection of Tehtris EDR events
=> Tehtris: add documentation

docs/xdr/features/collect/integrations/endpoint/windows.md
Update link to download Florian's Roth conf
=> Link-modification

_shared_content/operations_center/integrations/google_cloud.md
Change link to service account Google documentation
=> Updating-link

docs/xdr/features/collect/integrations/cloud_and_saas/okta_system_log.md, mkdocs.yml
add documentation for the system log's format
=> Okta: add documentation

docs/xdr/features/investigate/alerts.md
=> Change alert urgency

docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md, docs/xdr/features/collect/integrations/endpoint/cybereason_malop_activity.md, mkdocs.yml
- Rename the old documentation as Malop activities
- Create the documentation for the new integration
=> Cybereason: add new integration

docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
As the beta flag in the title doesn't work (the title of the page come from the menu), add a section to advise about the status of the format
=> Cybereason: add warning

docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_waf.md
=> AWS: fix WAF documentation

docs/xdr/features/collect/integrations/endpoint/sekoiaio.md
Improve the uninstall part of the documentation of the agent so it is compliant with new and old versions of the agent.
=> feat: Improve uninstall doc for the agent

docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
fix the link to the Cybereason symphony module
=> Cybereason: fix the link to the Cybereason symphony module

docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_waf.md
Remove Beta version note of AWS WAF
Fix punctuation
=> AWS: remove Beta version note of AWS WAF

docs/xdr/FAQ.md
Adding 
- Alert & IP section
- Alert Q/A
=> Update FAQ - adding Alert QA.md

docs/xdr/features/collect/integrations/cloud_and_saas/netskope_events.md, mkdocs.yml
Add the documentation to configure the collect of Netskope Events
=> Netskope: add documentation

docs/xdr/features/detect/rules_catalog.md, docs/xdr/features/investigate/alerts.md
=> Add similarity strategy

docs/xdr/features/collect/integrations/endpoint/sekoiaio.md
Replace old IP  `145.239.192.38`  for new IP  `51.159.9.95`
=> Update IP of SEKOIA.IO Endpoint Agent

mkdocs.yml
=> Add footer information

docs/xdr/features/collect/integrations/cloud_and_saas/netskope_events.md
Remove the beta notice in the documentation
=> Netskope: remove beta notice

docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
Specify the minimal rights the user used for the connector should have.
=> Cybereason: add rights

docs/xdr/features/collect/integrations/application/freeradius.md, mkdocs.yml
Add the documentation for FreeRADIUS.
=> FreeRADIUS: add doc

docs/xdr/features/integrations/fortisoar.md, mkdocs.yml
Add documentation for our FortiSOAR connector
=> FortiSOAR: add documentation

docs/getting_started/account_security.md, docs/getting_started/securitytokens.md
Must remove similar content from account-security.md
=> Add security tokens page

docs/xdr/xdr_quick_start.md
=> Small bug fix on quick start

docs/xdr/features/collect/integrations/network/sonicwall_fw.md
=> Fix Sonicwall documentation

docs/xdr/features/collect/integrations/endpoint/linux.md
Deprecate Linux Format in flavor of alternative ones
=> Linux: deprecate format

docs/xdr/features/collect/integrations/cloud_and_saas/office365/o365.md
* add information about wait time for the first events to be retrieved.
=> update(o365-wait): add important info about time to wait

docs/xdr/features/collect/integrations/network/cisco/cisco_meraki_mx.md, mkdocs.yml
Add the documentation to forward logs from Cisco Meraki MX
=> Cisco: Add documentation about Meraki MX

docs/xdr/features/collect/ingestion_methods/sekoiaio_docker_concentrator.md
* Move the docker installation section for more readability
=> update(docker-concentrator): move docker installation section

docs/xdr/features/collect/integrations/network/paloalto.md
Add section to explain how to forward logs through Palo Alto Cortex Data Lake
=> PaloAlto:  Explain how to forward logs through CDL

docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
Remove the beta note in the documentation
=> Cybereason: Out of Beta

docs/xdr/features/collect/integrations/email/postfix.md
fix the path to the auto generated documentation
=> Postfix: fix the autogenerated postfix documentation

mkdocs.yml
TheHive integration page is missing so it should be removed
=> removing TheHive integration

docs/xdr/features/collect/integrations/network/checkpoint.md
Add reference to the CEF format
=> Update checkpoint configuration

docs/xdr/features/collect/integrations/network/cisco/cisco_wsa.md
Explain how to forward Cisco WSA logs to SEKOIA.IO
=> Cisco: fix Cisco Web Security Appliance

_shared_content/operations_center/integrations/aws_create_s3_notification.md, _shared_content/operations_center/integrations/aws_create_sqs_queue.md, docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_cloudtrail.md, docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_flow_logs.md, docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_s3_logs.md, docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_waf.md
Outsource sections about the creation of a sqs queue and a S3 notification in shared document
Fix punctuation
=> AWS: mutualize shared content

docs/xdr/features/collect/integrations/network/opnsense.md, docs/xdr/features/collect/integrations/network/pfsense.md, mkdocs.yml
Add the missing documentation for OPNSense and pfSense.
=> BSD: add docs for OPNSense and pfSense

_shared_content/ioccollections.md
Edit the listing so that the 1, 2, 3 in the file import are logical
=> Enhance listing on IOC Collections

docs/xdr/features/collect/integrations/email/cisco_esa.md, mkdocs.yml
Add the documentation for Cisco ESA
=> Cisco: add Cisco ESA documentation

docs/xdr/features/collect/ingestion_methods/rsyslog.md, docs/xdr/features/collect/ingestion_methods/syslog-ng.md
Change the IP of `intake.sekoia.io` with the new one
=> update(ip-intake-sekoia): modify IP

docs/xdr/features/collect/integrations/application/rsa_securid.md, mkdocs.yml
Add the documentation to set up the forwarding of logs to SEKOIA.IO
=> RSA: add documentation

docs/xdr/features/collect/integrations/endpoint/winlogbeat.md, docs/xdr/features/collect/integrations/network/cisco/cisco_meraki_mx.md
Remove from beta the formats winlogbeat and cisco Meraki
=> Formats: Out of beta

docs/xdr/features/collect/integrations/email/vade.md
I have added the information regarding the module that need to be activated to be able to collect logs from Vade.
=> Update of Vade documentation

docs/xdr/features/collect/integrations/endpoint/sentinelone.md, docs/xdr/features/collect/integrations/endpoint/sentinelone_deepvisibility.md, mkdocs.yml
* Deprecate SentinelOne Deep Visibility integration
* Ability to use Service Users in SentinelOne management console
=> Update SentinelOne documentation

docs/cti/develop/rest_api/edl-gateway.md, mkdocs.yml
Reverts SEKOIA-IO/documentation#1067
=> Revert "Remove EDL-Gateway REST API documentation"

docs/xdr/features/collect/ingestion_methods/sekoiaio_forwarder.md, mkdocs.yml
* renamed to Sekoia.io Fowarder
* Add a English tutorial in French and English
* Removed BETA mode
* Renamed SEKOIA.IO to Sekoia.io
=> feat(update-sekoia-forwarder): renamed and add videos

docs/xdr/features/collect/integrations/cloud_and_saas/ogo_shield.md, mkdocs.yml
=> OGO: add documentation

docs/xdr/features/collect/integrations/cloud_and_saas/ubika_waap.md, mkdocs.yml
Adding Ubika WAAP Gateway docs
=> Add Ubika docs

docs/xdr/features/collect/integrations/cloud_and_saas/github_audit_logs.md
=> Github: add beta mention

docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-access-requests.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-audit-logs.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-dns.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-http.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-network.md
add the beta mention in the documentation
=> Cloudflare: add the beta mention in the documentation

docs/xdr/features/collect/integrations/network/cisco/cisco_ise.md
Hi @squioc, this's the documentation for Cisco ISE. Can you review it please.
=> Add cisco ISE documentation to cisco folder

docs/xdr/features/collect/integrations/cloud_and_saas/office365/microsoft_365_defender.md, docs/xdr/features/collect/integrations/cloud_and_saas/office365/o365.md, mkdocs.yml
Modify : 
- `Microsoft Defender for Endpoints" into `Microsoft 365 Defender`
- Add event types supported
=> feat(m365defender): rename the integration and add event types

docs/xdr/features/collect/integrations/email/vade.md
Update the Vade for M365 documentation to provide clearer instructions on how to set up the integration
=> Update Vade for M365 documentation

docs/xdr/features/collect/integrations/endpoint/sekoiaio.md
+ Move Built-in rules at the bottom (for readiness)
=> Add download link in Agent doc page

docs/xdr/features/collect/ingestion_methods/sekoiaio_forwarder.md
=> Fix broken link forwarder

docs/xdr/features/collect/integrations/cloud_and_saas/google/google_drive_reports.md, mkdocs.yml
- Add Google Drive Reports Documentation
=> Add the google reports drive documentation

docs/xdr/features/collect/integrations/application/rsa_securid.md, docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_guardduty.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-access-requests.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-audit-logs.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-dns.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-http.md, docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-network.md, docs/xdr/features/collect/integrations/cloud_and_saas/duo_security.md, docs/xdr/features/collect/integrations/cloud_and_saas/github_audit_logs.md, docs/xdr/features/collect/integrations/cloud_and_saas/ogo_shield.md, docs/xdr/features/collect/integrations/cloud_and_saas/salesforce.md, docs/xdr/features/collect/integrations/cloud_and_saas/sophos_threat_analysis_center.md, docs/xdr/features/collect/integrations/cloud_and_saas/ubika_waap.md, docs/xdr/features/collect/integrations/email/cisco_esa.md, docs/xdr/features/collect/integrations/endpoint/crowdstrike_telemetry.md, docs/xdr/features/collect/integrations/endpoint/darktrace_threat_visualizer.md, docs/xdr/features/collect/integrations/endpoint/sentinelone_cloudfunnel2.0.md, docs/xdr/features/collect/integrations/endpoint/trellix_epo.md, docs/xdr/features/collect/integrations/endpoint/trend_micro/trend_micro_apex_one.md, docs/xdr/features/collect/integrations/endpoint/vmware/vmware_esxi.md, docs/xdr/features/collect/integrations/endpoint/vmware/vmware_vcenter.md, docs/xdr/features/collect/integrations/network/cisco/cisco_nx_os.md, docs/xdr/features/collect/integrations/network/citrix_adc.md, docs/xdr/features/collect/integrations/network/sonicwall_fw.md, docs/xdr/features/collect/integrations/network/varonis_data_security.md
Change the message for integrations in beta with something less alarming
=> Beta: change the message for beta integrations

_shared_content/automate/playbooks-on-premises.md
Add a tip for hosts that needs a proxy to access Sekoia.io
=> feat: Add proxy information on hello-sekoia command

_shared_content/automate/playbooks-on-premises.md
=> Add host requirements for Playbooks On-prem

docs/xdr/features/collect/integrations/endpoint/windows.md
=> NXLog limitation with special characters

docs/xdr/features/collect/integrations/email/vade_cloud.md
Based on ticket 2280 experience
=> Update vade_cloud documentation

docs/xdr/features/collect/integrations/application/alsid.md, docs/xdr/features/collect/integrations/application/apache.md, docs/xdr/features/collect/integrations/application/bind.md, docs/xdr/features/collect/integrations/application/dhcpd.md, docs/xdr/features/collect/integrations/application/haproxy.md, docs/xdr/features/collect/integrations/application/microsoft_iis.md, docs/xdr/features/collect/integrations/application/nginx.md, docs/xdr/features/collect/integrations/application/openldap.md, docs/xdr/features/collect/integrations/application/openssh.md, docs/xdr/features/collect/integrations/application/unbound.md, docs/xdr/features/collect/integrations/cloud_and_saas/cisco_umbrella/umbrella_dns.md, docs/xdr/features/collect/integrations/cloud_and_saas/cisco_umbrella/umbrella_ip.md, docs/xdr/features/collect/integrations/cloud_and_saas/cisco_umbrella/umbrella_proxy.md, docs/xdr/features/collect/integrations/email/postfix.md, docs/xdr/features/collect/integrations/email/spamassassin.md, docs/xdr/features/collect/integrations/endpoint/auditbeat_linux.md, docs/xdr/features/collect/integrations/endpoint/log_insight_windows.md, docs/xdr/features/collect/integrations/endpoint/windows.md, docs/xdr/features/collect/integrations/generic/cef.md, docs/xdr/features/collect/integrations/network/netfilter.md, docs/xdr/features/collect/integrations/network/skyhigh_secure_web_gateway.md, docs/xdr/features/collect/integrations/network/squid.md, docs/xdr/features/collect/integrations/network/suricata.md, docs/xdr/features/collect/integrations/network/trellix_nx.md, docs/xdr/features/collect/integrations/network/vectra.md, docs/xdr/features/collect/integrations/network/wallix.md, docs/xdr/features/collect/integrations/network/watchguard_firebox.md, docs/xdr/features/collect/integrations/network/zeek.md, docs/xdr/xdr_quick_start.md
Fix https://github.com/SEKOIA-IO/documentation/pull/1535
=> Fix dead link to Syslog / Https pages

docs/xdr/features/collect/integrations/endpoint/sekoiaio.md
Raphael, please check the edits I offer to introduce. Feel free to ping me if I need to change something.
=> Update Sekoia.io Endpoint Agent sekoiaio.md

docs/getting_started/regions.md
=> fix(typo-region): eua1 into uae1

docs/xdr/features/collect/ingestion_methods/syslog/sekoiaio_forwarder.md
- Added doc for multi-region
- Added section to add a custom conf file
- Updated the docker-compose file suggested
This PR needs this PR https://github.com/SEKOIA-IO/sekoiaio-docker-concentrator/pull/21 to be merged first.
=> feat(feat/forwarder-add-multi-region): multi-region + custom conf

_shared_content/intelligence_center/integrations/index.md, _shared_content/intelligence_center/integrations/threatquotient.md, mkdocs.yml
https://chat.sekoia.io/sekoia/pl/e7grxqwf17fz9po6ut5jexixoa
=> Add ThreatQuotient to the list of Integrations

mkdocs.yml
https://chat.sekoia.io/sekoia/pl/bicgykpkrbbxdyfbae6w1iqrto
=> change ALSID page title

docs/xdr/features/collect/integrations/network/f5-big-ip.md
Add the list of modules from which the integration will accept events
=> F5: add the modules supported by the integration

docs/xdr/features/collect/integrations/cloud_and_saas/ogo_shield.md
Update the instruction according to [their documentation](https://help.ogosecurity.com/help/log-export)
=> OGO: update the way to configuration the log forwarding for OGO

docs/getting_started/community-create_sub_com.md
https://chat.sekoia.io/sekoia/pl/csi7p4yuft8tdcxptwkdjpep4e
=> update community creation with new nav

docs/xdr/features/collect/integrations/network/skyhigh_secure_web_gateway.md
Use a log concentrator as intermediate for the log forwarding
=> SkyHighSecureWebGateway: change the way to forward the logs to sekoi

docs/xdr/features/collect/assets.md
Update the documentation to reflect this recent change.
=> Remove Host <> IP rules from the documentation

docs/xdr/features/collect/integrations/cloud_and_saas/office365/o365.md
Change the documentation to explain how to set up the integration with the connector.
=> Office365: change the procedure to create a new integration

docs/xdr/develop/quickstart.md, docs/xdr/develop/rest_api/query_builder.md, mkdocs.yml
Add the documentation of the Query Builder API
=> feat: add query builder documentation

docs/xdr/develop/rest_api/assets.md, mkdocs.yml
https://chat.sekoia.io/sekoia/pl/xe6bhthny7nd5cczdtsy5rtu9a
=> Remove Assets v1 and rename v2 + remove Beta

docs/xdr/features/collect/integrations/network/efficientip_solidserver_ddi.md
- add beta mention
- add supported versions
- add supported events
=> EfficientIP: improve the documentation

scripts/update_mkdocs/templates/intake.md.jinja, scripts/update_mkdocs/templates/sample.md.jinja, scripts/update_mkdocs/update_mkdocs.py
- Added a section for sample events
- Modified the test section description
=> Added a section for sample events

docs/xdr/features/collect/integrations/cloud_and_saas/google/google_reports.md
add a warning about login events for the Google Workspace integration
=> doc(Google): add a warning about login events for the Google Workspace

_shared_content/operations_center/integrations/event_hub.md
[related to this](https://sekoia8055.zendesk.com/agent/tickets/4047)
=> fix clickable image

docs/xdr/features/collect/assets.md
Reflect latest changes on the asset discovery in the documentation
=> Update asset discovery rule description

docs/integration/ingestion_methods/syslog/secured_forwarding.md
related to https://sekoia8055.zendesk.com/agent/tickets/4221
=> fix for missing package install

docs/integration/categories/endpoint/pradeo_mtd.md, mkdocs.yml
Add a non-completed version of the Pradeo MTD documentation
=> Pradeo: add a first version of the pradeo documentation

docs/xdr/usecases/use_your_own_cti.md, mkdocs.yml
[Link to the page](https://storage.gra.cloud.ovh.net/v1/AUTH_741841e1c7da4c50a76152cbc2609bd1/sekoiaio-documentation-previews/1991/xdr/usecases/use_your_own_cti/)
=> feat: Use case to push CTI

docs/integration/action_library/endpoint/withsecure.md
https://github.com/SekoiaLab/integration/issues/178
=> Add docs for WithSecure response actions

docs/integration/categories/endpoint/pradeo_mtd.md
- add the configuration section
- add the samples
- add the extracted fields
=> Pradeo: update documentation

docs/xdr/FAQ.md
We don't want our customers to use our domain *and* setup IP filtering without being aware of the risks.
=> feat(IP): change IP policy

docs/integration/ingestion_methods/https/format.md
- Add a description of the new `/many` endpoint
- Reorganize the different sections
=> HTTP Ingestion: add /many endpoint + some reorganizations

docs/integration/categories/network_security/watchguard_firebox.md
Related to this ticket:
https://sekoia8055.zendesk.com/agent/tickets/4785
=> add warning to not have timestamp issues

docs/integration/categories/applicative/google_reports.md
Add new services to google report documentation
=> Update doc with new services

docs/integration/categories/iam/alsid.md, mkdocs.yml
Rename the integration to Tenable Exposure Identity / Alsid
=> Tenable Exposure Identity: rename the integration

docs/xdr/usecases/playbook/implement_blocklist.md
https://sekoia8055.zendesk.com/agent/tickets/5278
=> fix_needed_permission_for_blocklist

docs/integration/categories/network_security/paloalto.md
rename Palo Alto Cortex DataLake into Palo Alto Strata Logging service, the new name of this product
=> PaloAlto: rename Palo Alto Cortex DataLake into Palo Alto Strata Logging service

docs/xdr/FAQ.md
Update the documentation regarding the rate limit rules enforced.
=> feat(FAQ): Improve precision of limits on requests rate

docs/integration/categories/endpoint/sekoiaio.md
https://chat.sekoia.io/sekoia/pl/du4jc1y35jfkjp8o316rw4br1e
=> add windows server 2025

docs/integration/categories/email/mimecast_email_security.md
- Add a note about the frequency of the collect
- Add the list of collected datasets
:warning: Please don't merge this PR before Tuesday 28th
=> Mimecast: Update documentation

docs/integration/categories/network/sesameit_jizo.md
Remove the beta mention in the documentation
=> SesameIT Jizo: out of beta

docs/integration/categories/email/mimecast_email_security.md
related to https://sekoia8055.zendesk.com/agent/tickets/5664
=> add missing permission

docs/integration/categories/applicative/google_cloud_audit.md, docs/integration/categories/applicative/google_reports.md, mkdocs.yml
main issue : [Issue](https://github.com/SekoiaLab/integration/issues/391#event-16191155665)
=> Change the name of title

docs/xdr/features/investigate/sekoia_operating_language.md, mkdocs.yml
https://storage.gra.cloud.ovh.net/v1/AUTH_741841e1c7da4c50a76152cbc2609bd1/sekoiaio-documentation-previews/2194/xdr/features/investigate/sekoia_operating_language/
=> Create Sekoia Operating Language documentation

docs/getting_started/notifications-Examples.md, docs/integration/develop_integration/automation/create_a_module.md
pytest is broken without the v1
=> update pydantic version in doc sample

docs/integration/categories/endpoint/microsoft_intune.md
fix https://github.com/SekoiaLab/integration/issues/448
=> Add supported application or feature

docs/integration/categories/applicative/google_reports.md
Main Issue : [Issue](https://github.com/SekoiaLab/integration/issues/342)
=> Add a new important part

docs/integration/categories/applicative/google_reports.md
add more details about the events collected and about the delay of the events
=> Google: add more details

_shared_content/operations_center/integrations/aws_create_s3_sqs_notification.md
List permissions required for the account used to read the messages and to fetch the objects
=> AWS: list permissions required for the account

docs/integration/categories/endpoint/trend_micro_apex_one.md, mkdocs.yml
https://github.com/SekoiaLab/integration/issues/444
=> Trend Micro Apex One - rename

docs/integration/categories/network_security/zscaler_zia.md
Closes [516](https://github.com/SekoiaLab/integration/issues/516)
=> Fix: Docs update zscaler (516)

docs/xdr/features/detect/sigma.md
https://storage.gra.cloud.ovh.net/v1/AUTH_741841e1c7da4c50a76152cbc2609bd1/sekoiaio-documentation-previews/2266/xdr/features/detect/sigma/#detection-on-specific-time-windows
=> Add time-based sigma documentation

docs/integration/categories/network/beyondtrust_pra.md
https://github.com/SekoiaLab/integration/issues/537
=> BeyondTrust - add link

docs/integration/develop_integration/formats/taxonomy.md
Add a note to describe the related field an how it works.
Main issue : [issue](https://github.com/SekoiaLab/platform/issues/60802)
=> Add remark about related field

docs/xdr/features/investigate/sekoia_operating_language.md
https://storage.gra.cloud.ovh.net/v1/AUTH_741841e1c7da4c50a76152cbc2609bd1/sekoiaio-documentation-previews/2298/xdr/features/investigate/sekoia_operating_language/
=> Add not operator, case-insensitive variants, regex, nested in, toscalar

docs/integration/categories/network_security/extrahop_revealx_360.md
https://github.com/SekoiaLab/integration/issues/457
=> Improve docs for ExtraHop Reveal(x) 360

docs/integration/categories/email/o365.md, docs/integration/categories/email/o365_appendix.md
linked to ticket https://sekoia8055.zendesk.com/agent/tickets/6417
=> recovering old file that was lost in translation

docs/integration/categories/endpoint/paloalto_cortex_edr.md
I found some duplicated paragraphs in this documentation
=> Delete some duplicated paragraphs

docs/integration/categories/endpoint/bitdefender_gravityzone.md
Fix the script (mainly the intake key in base64)
=> BitDefender: fix the script to create PushEventSettings

docs/integration/categories/applicative/lockself.md
- `us` -> the LockSelf Support Team
- `We` ->  `They`
=> LockSelf: some wording changes

docs/integration/categories/network_security/cisco_identity_services_engine_ise.md
As discussed on mattermost last time, there's no details about supported features.
=> Update supported features

docs/integration/categories/network_security/olfeo_saas.md, mkdocs.yml
Related PR : [PR](https://github.com/SEKOIA-IO/documentation/pull/2420)
=> feat(olfeo): add for the first time the olfeo saas documentation

docs/xdr/features/investigate/sekoia_operating_language.md
https://storage.gra.cloud.ovh.net/v1/AUTH_741841e1c7da4c50a76152cbc2609bd1/sekoiaio-documentation-previews/2502/xdr/features/investigate/sekoia_operating_language/#string-tolower
=> Add doc for tolower(), toupper(), round(), iff(), coalesce() and format_datetime()

docs/integration/categories/endpoint/crowdstrike_falcon.md
As we updated the way the connector collects Vertex, I update the documentation consequently
=> CrowdStrike: add the documentation about how to collect Vertex
